<?php

use Illuminate\Database\Seeder;

class CanvasTagsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('canvas_tags')->delete();
        
        \DB::table('canvas_tags')->insert(array (
            0 => 
            array (
                'id' => 2,
                'tag' => 'masks',
                'title' => 'Mask Production',
                'subtitle' => 'Mask making in all its glory',
                'meta_description' => 'Masks making through clay sculpture and silicon molding process',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            1 => 
            array (
                'id' => 3,
                'tag' => 'Props',
                'title' => 'Prop Making',
                'subtitle' => 'Cosplay accessories ',
                'meta_description' => 'Props for costume and character work',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:47:17',
                'updated_at' => '2017-05-22 01:47:17',
            ),
            2 => 
            array (
                'id' => 4,
                'tag' => 'Costumes',
                'title' => 'Costume Making',
                'subtitle' => 'Costume production ',
                'meta_description' => 'Costume creation typically is a large degree of pattern creation and sewing various textiles ',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:50:35',
                'updated_at' => '2017-05-22 01:50:35',
            ),
            3 => 
            array (
                'id' => 5,
                'tag' => 'Making',
                'title' => 'Making',
                'subtitle' => 'To create a thing.',
                'meta_description' => 'Making or to make is what a maker does with everything at their disposal',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:54:19',
                'updated_at' => '2017-05-22 01:54:19',
            ),
            4 => 
            array (
                'id' => 6,
                'tag' => 'Natetheaverage',
                'title' => 'Natetheaverage',
                'subtitle' => 'Natetheaverage',
                'meta_description' => 'Natetheaverage',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            5 => 
            array (
                'id' => 7,
                'tag' => 'colorado',
                'title' => 'colorado',
                'subtitle' => 'colorado',
                'meta_description' => 'colorado',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            6 => 
            array (
                'id' => 8,
                'tag' => 'the box',
                'title' => 'the box',
                'subtitle' => 'the box',
                'meta_description' => 'the box',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            7 => 
            array (
                'id' => 9,
                'tag' => 'soho',
                'title' => 'soho',
                'subtitle' => 'soho',
                'meta_description' => 'soho',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            8 => 
            array (
                'id' => 10,
                'tag' => 'nyc',
                'title' => 'nyc',
                'subtitle' => 'nyc',
                'meta_description' => 'nyc',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            9 => 
            array (
                'id' => 11,
                'tag' => 'the act',
                'title' => 'the act',
                'subtitle' => 'the act',
                'meta_description' => 'the act',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            10 => 
            array (
                'id' => 12,
                'tag' => 'las vegas',
                'title' => 'las vegas',
                'subtitle' => 'las vegas',
                'meta_description' => 'las vegas',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            11 => 
            array (
                'id' => 13,
                'tag' => 'mykonos',
                'title' => 'mykonos',
                'subtitle' => 'mykonos',
                'meta_description' => 'mykonos',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            12 => 
            array (
                'id' => 14,
                'tag' => 'flash',
                'title' => 'flash',
                'subtitle' => 'flash',
                'meta_description' => 'flash',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            13 => 
            array (
                'id' => 15,
                'tag' => 'as3',
                'title' => 'as3',
                'subtitle' => 'as3',
                'meta_description' => 'as3',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            14 => 
            array (
                'id' => 16,
                'tag' => 'svg',
                'title' => 'svg',
                'subtitle' => 'svg',
                'meta_description' => 'svg',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            15 => 
            array (
                'id' => 17,
                'tag' => 'animation',
                'title' => 'animation',
                'subtitle' => 'animation',
                'meta_description' => 'animation',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            16 => 
            array (
                'id' => 18,
                'tag' => 'motion graphics',
                'title' => 'motion graphics',
                'subtitle' => 'motion graphics',
                'meta_description' => 'motion graphics',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            17 => 
            array (
                'id' => 19,
                'tag' => 'insomniac',
                'title' => 'insomniac',
                'subtitle' => 'insomniac',
                'meta_description' => 'insomniac',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            18 => 
            array (
                'id' => 20,
                'tag' => 'edc',
                'title' => 'edc',
                'subtitle' => 'edc',
                'meta_description' => 'edc',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            19 => 
            array (
                'id' => 21,
                'tag' => 'electric daisy carnival',
                'title' => 'electric daisy carnival',
                'subtitle' => 'electric daisy carnival',
                'meta_description' => 'electric daisy carnival',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            20 => 
            array (
                'id' => 22,
                'tag' => 'ultra',
                'title' => 'ultra',
                'subtitle' => 'ultra',
                'meta_description' => 'ultra',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            21 => 
            array (
                'id' => 23,
                'tag' => 'electronic music',
                'title' => 'electronic music',
                'subtitle' => 'electronic music',
                'meta_description' => 'electronic music',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            22 => 
            array (
                'id' => 24,
                'tag' => 'house music',
                'title' => 'house music',
                'subtitle' => 'house music',
                'meta_description' => 'house music',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            23 => 
            array (
                'id' => 25,
                'tag' => 'stilts',
                'title' => 'stilts',
                'subtitle' => 'stilts',
                'meta_description' => 'stilts',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            24 => 
            array (
                'id' => 26,
                'tag' => 'stilt waliking',
                'title' => 'stilt waliking',
                'subtitle' => 'stilt waliking',
                'meta_description' => 'stilt waliking',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            25 => 
            array (
                'id' => 27,
                'tag' => 'circus',
                'title' => 'circus',
                'subtitle' => 'circus',
                'meta_description' => 'circus',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            26 => 
            array (
                'id' => 28,
                'tag' => 'house dance',
                'title' => 'house dance',
                'subtitle' => 'house dance',
                'meta_description' => 'house dance',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            27 => 
            array (
                'id' => 29,
                'tag' => 'dance,bboy',
                'title' => 'dance,bboy',
                'subtitle' => 'dance,bboy',
                'meta_description' => 'dance,bboy',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            28 => 
            array (
                'id' => 30,
                'tag' => 'breakdancer',
                'title' => 'breakdancer',
                'subtitle' => 'breakdancer',
                'meta_description' => 'breakdancer',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            29 => 
            array (
                'id' => 31,
                'tag' => 'breakdancing',
                'title' => 'breakdancing',
                'subtitle' => 'breakdancing',
                'meta_description' => 'breakdancing',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            30 => 
            array (
                'id' => 32,
                'tag' => 'popping',
                'title' => 'popping',
                'subtitle' => 'popping',
                'meta_description' => 'popping',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            31 => 
            array (
                'id' => 33,
                'tag' => 'quadrocopter',
                'title' => 'quadrocopter',
                'subtitle' => 'quadrocopter',
                'meta_description' => 'quadrocopter',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            32 => 
            array (
                'id' => 34,
                'tag' => 'swarm',
                'title' => 'swarm',
                'subtitle' => 'swarm',
                'meta_description' => 'swarm',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            33 => 
            array (
                'id' => 35,
                'tag' => 'robots',
                'title' => 'robots',
                'subtitle' => 'robots',
                'meta_description' => 'robots',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            34 => 
            array (
                'id' => 36,
                'tag' => 'drones',
                'title' => 'drones',
                'subtitle' => 'drones',
                'meta_description' => 'drones',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            35 => 
            array (
                'id' => 37,
                'tag' => 'microcontroller',
                'title' => 'microcontroller',
                'subtitle' => 'microcontroller',
                'meta_description' => 'microcontroller',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            36 => 
            array (
                'id' => 38,
                'tag' => 'arduino',
                'title' => 'arduino',
                'subtitle' => 'arduino',
                'meta_description' => 'arduino',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            37 => 
            array (
                'id' => 39,
                'tag' => 'intel edison',
                'title' => 'intel edison',
                'subtitle' => 'intel edison',
                'meta_description' => 'intel edison',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            38 => 
            array (
                'id' => 40,
                'tag' => 'python',
                'title' => 'python',
                'subtitle' => 'python',
                'meta_description' => 'python',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            39 => 
            array (
                'id' => 41,
                'tag' => 'prototyping',
                'title' => 'prototyping',
                'subtitle' => 'prototyping',
                'meta_description' => 'prototyping',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            40 => 
            array (
                'id' => 42,
                'tag' => 'maker',
                'title' => 'maker',
                'subtitle' => 'maker',
                'meta_description' => 'maker',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            41 => 
            array (
                'id' => 43,
                'tag' => 'sculpting',
                'title' => 'sculpting',
                'subtitle' => 'sculpting',
                'meta_description' => 'sculpting',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            42 => 
            array (
                'id' => 44,
                'tag' => 'mold making',
                'title' => 'mold making',
                'subtitle' => 'mold making',
                'meta_description' => 'mold making',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            43 => 
            array (
                'id' => 45,
                'tag' => 'sfx',
                'title' => 'sfx',
                'subtitle' => 'sfx',
                'meta_description' => 'sfx',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            44 => 
            array (
                'id' => 46,
                'tag' => 'molding',
                'title' => 'molding',
                'subtitle' => 'molding',
                'meta_description' => 'molding',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            45 => 
            array (
                'id' => 47,
                'tag' => 'life cast',
                'title' => 'life cast',
                'subtitle' => 'life cast',
                'meta_description' => 'life cast',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            46 => 
            array (
                'id' => 48,
                'tag' => 'makeup',
                'title' => 'makeup',
                'subtitle' => 'makeup',
                'meta_description' => 'makeup',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            47 => 
            array (
                'id' => 49,
                'tag' => 'treehouse',
                'title' => 'treehouse',
                'subtitle' => 'treehouse',
                'meta_description' => 'treehouse',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            48 => 
            array (
                'id' => 50,
                'tag' => 'build',
                'title' => 'build',
                'subtitle' => 'build',
                'meta_description' => 'build',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            49 => 
            array (
                'id' => 51,
                'tag' => 'create',
                'title' => 'create',
                'subtitle' => 'create',
                'meta_description' => 'create',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            50 => 
            array (
                'id' => 52,
                'tag' => 'direct',
                'title' => 'direct',
                'subtitle' => 'direct',
                'meta_description' => 'direct',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            51 => 
            array (
                'id' => 53,
                'tag' => 'shirt printing',
                'title' => 'shirt printing',
                'subtitle' => 'shirt printing',
                'meta_description' => 'shirt printing',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            52 => 
            array (
                'id' => 54,
                'tag' => 'direction',
                'title' => 'direction',
                'subtitle' => 'direction',
                'meta_description' => 'direction',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            53 => 
            array (
                'id' => 55,
                'tag' => 'acting',
                'title' => 'acting',
                'subtitle' => 'acting',
                'meta_description' => 'acting',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            54 => 
            array (
                'id' => 56,
                'tag' => 'powerrisers',
                'title' => 'powerrisers',
                'subtitle' => 'powerrisers',
                'meta_description' => 'powerrisers',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            55 => 
            array (
                'id' => 57,
                'tag' => 'jumping stilts',
                'title' => 'jumping stilts',
                'subtitle' => 'jumping stilts',
                'meta_description' => 'jumping stilts',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            56 => 
            array (
                'id' => 58,
                'tag' => 'php',
                'title' => 'php',
                'subtitle' => 'php',
                'meta_description' => 'php',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            57 => 
            array (
                'id' => 59,
                'tag' => 'vuejs',
                'title' => 'vuejs',
                'subtitle' => 'vuejs',
                'meta_description' => 'vuejs',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            58 => 
            array (
                'id' => 60,
                'tag' => 'laravel',
                'title' => 'laravel',
                'subtitle' => 'laravel',
                'meta_description' => 'laravel',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            59 => 
            array (
                'id' => 61,
                'tag' => 'html',
                'title' => 'html',
                'subtitle' => 'html',
                'meta_description' => 'html',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            60 => 
            array (
                'id' => 62,
                'tag' => 'css',
                'title' => 'css',
                'subtitle' => 'css',
                'meta_description' => 'css',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            61 => 
            array (
                'id' => 63,
                'tag' => 'js',
                'title' => 'js',
                'subtitle' => 'js',
                'meta_description' => 'js',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            62 => 
            array (
                'id' => 64,
                'tag' => 'ec2016',
                'title' => 'ec2016',
                'subtitle' => 'ec2016',
                'meta_description' => 'ec2016',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            63 => 
            array (
                'id' => 65,
                'tag' => 'npm',
                'title' => 'npm',
                'subtitle' => 'npm',
                'meta_description' => 'npm',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            64 => 
            array (
                'id' => 66,
                'tag' => 'node',
                'title' => 'node',
                'subtitle' => 'node',
                'meta_description' => 'node',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            65 => 
            array (
                'id' => 67,
                'tag' => 'bootstrap',
                'title' => 'bootstrap',
                'subtitle' => 'bootstrap',
                'meta_description' => 'bootstrap',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            66 => 
            array (
                'id' => 68,
                'tag' => 'flexbot',
                'title' => 'flexbot',
                'subtitle' => 'flexbot',
                'meta_description' => 'flexbot',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            67 => 
            array (
                'id' => 69,
                'tag' => 'webkit',
                'title' => 'webkit',
                'subtitle' => 'webkit',
                'meta_description' => 'webkit',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            68 => 
            array (
                'id' => 70,
                'tag' => 'gulp',
                'title' => 'gulp',
                'subtitle' => 'gulp',
                'meta_description' => 'gulp',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            69 => 
            array (
                'id' => 71,
                'tag' => 'golang',
                'title' => 'golang',
                'subtitle' => 'golang',
                'meta_description' => 'golang',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            70 => 
            array (
                'id' => 72,
                'tag' => 'electron',
                'title' => 'electron',
                'subtitle' => 'electron',
                'meta_description' => 'electron',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            71 => 
            array (
                'id' => 73,
                'tag' => 'autonomus',
                'title' => 'autonomus',
                'subtitle' => 'autonomus',
                'meta_description' => 'autonomus',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            72 => 
            array (
                'id' => 74,
                'tag' => 'love',
                'title' => 'love',
                'subtitle' => 'love',
                'meta_description' => 'love',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            73 => 
            array (
                'id' => 75,
                'tag' => 'Brian Taylor',
                'title' => 'Brian Taylor',
                'subtitle' => 'Brian Taylor',
                'meta_description' => 'Brian Taylor',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            74 => 
            array (
                'id' => 76,
                'tag' => 'Jude ohYea Leite',
                'title' => 'Jude ohYea Leite',
                'subtitle' => 'Jude ohYea Leite',
                'meta_description' => 'Jude ohYea Leite',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            75 => 
            array (
                'id' => 77,
                'tag' => 'Jett TickTock Leite',
                'title' => 'Jett TickTock Leite',
                'subtitle' => 'Jett TickTock Leite',
                'meta_description' => 'Jett TickTock Leite',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            76 => 
            array (
                'id' => 78,
                'tag' => 'Global Dance Festival',
                'title' => 'Global Dance Festival',
                'subtitle' => 'Global Dance Festival',
                'meta_description' => 'Global Dance Festival',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            77 => 
            array (
                'id' => 79,
                'tag' => 'Beyond Wonderland',
                'title' => 'Beyond Wonderland',
                'subtitle' => 'Beyond Wonderland',
                'meta_description' => 'Beyond Wonderland',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            78 => 
            array (
                'id' => 80,
                'tag' => 'Escape From Wonderland',
                'title' => 'Escape From Wonderland',
                'subtitle' => 'Escape From Wonderland',
                'meta_description' => 'Escape From Wonderland',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            79 => 
            array (
                'id' => 81,
                'tag' => 'Sonic Bloom',
                'title' => 'Sonic Bloom',
                'subtitle' => 'Sonic Bloom',
                'meta_description' => 'Sonic Bloom',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            80 => 
            array (
                'id' => 82,
                'tag' => 'skylab',
                'title' => 'skylab',
                'subtitle' => 'skylab',
                'meta_description' => 'skylab',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            81 => 
            array (
                'id' => 83,
                'tag' => 'Wildchild World',
                'title' => 'Wildchild World',
                'subtitle' => 'Wildchild World',
                'meta_description' => 'Wildchild World',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            82 => 
            array (
                'id' => 84,
                'tag' => 'Mirror Man',
                'title' => 'Mirror Man',
                'subtitle' => 'Mirror Man',
                'meta_description' => 'Mirror Man',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            83 => 
            array (
                'id' => 85,
                'tag' => 'Burning Man',
                'title' => 'Burning Man',
                'subtitle' => 'Burning Man',
                'meta_description' => 'Burning Man',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            84 => 
            array (
                'id' => 86,
                'tag' => 'Code',
                'title' => 'Code',
                'subtitle' => 'Code',
                'meta_description' => 'Code',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            85 => 
            array (
                'id' => 87,
                'tag' => 'Software',
                'title' => 'Software',
                'subtitle' => 'Software',
                'meta_description' => 'Software',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            86 => 
            array (
                'id' => 88,
                'tag' => 'github',
                'title' => 'github',
                'subtitle' => 'github',
                'meta_description' => 'github',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            87 => 
            array (
                'id' => 89,
                'tag' => 'Simon Hamerstine',
                'title' => 'Simon Hamerstine',
                'subtitle' => 'Simon Hamerstine',
                'meta_description' => 'Simon Hamerstine',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            88 => 
            array (
                'id' => 90,
                'tag' => 'workaholic',
                'title' => 'workaholic',
                'subtitle' => 'workaholic',
                'meta_description' => 'workaholic',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            89 => 
            array (
                'id' => 91,
                'tag' => 'javascript',
                'title' => 'javascript',
                'subtitle' => 'javascript',
                'meta_description' => 'javascript',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            90 => 
            array (
                'id' => 92,
                'tag' => 'crazyflie',
                'title' => 'crazyflie',
                'subtitle' => 'crazyflie',
                'meta_description' => 'crazyflie',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            91 => 
            array (
                'id' => 93,
                'tag' => 'meow wolf',
                'title' => 'meow wolf',
                'subtitle' => 'meow wolf',
                'meta_description' => 'meow wolf',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            92 => 
            array (
                'id' => 94,
                'tag' => 'Orange Peele',
                'title' => 'Orange Peele',
                'subtitle' => 'Orange Peele',
                'meta_description' => 'Orange Peele',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            93 => 
            array (
                'id' => 95,
                'tag' => 'Citric Acid Entertainment',
                'title' => 'Citric Acid Entertainment',
                'subtitle' => 'Citric Acid Entertainment',
                'meta_description' => 'Citric Acid Entertainment',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            94 => 
            array (
                'id' => 96,
                'tag' => 'crazyflie2',
                'title' => 'crazyflie2',
                'subtitle' => 'crazyflie2',
                'meta_description' => 'crazyflie2',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            95 => 
            array (
                'id' => 97,
                'tag' => 'lps',
                'title' => 'lps',
                'subtitle' => 'lps',
                'meta_description' => 'lps',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            96 => 
            array (
                'id' => 98,
                'tag' => 'loco positioning system',
                'title' => 'loco positioning system',
                'subtitle' => 'loco positioning system',
                'meta_description' => 'loco positioning system',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            97 => 
            array (
                'id' => 99,
                'tag' => 'paint',
                'title' => 'paint',
                'subtitle' => 'paint',
                'meta_description' => 'paint',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            98 => 
            array (
                'id' => 100,
                'tag' => 'painter',
                'title' => 'painter',
                'subtitle' => 'painter',
                'meta_description' => 'painter',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            99 => 
            array (
                'id' => 101,
                'tag' => 'air brush',
                'title' => 'air brush',
                'subtitle' => 'air brush',
                'meta_description' => 'air brush',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            100 => 
            array (
                'id' => 102,
                'tag' => 'foam sculpting',
                'title' => 'foam sculpting',
                'subtitle' => 'foam sculpting',
                'meta_description' => 'foam sculpting',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            101 => 
            array (
                'id' => 103,
                'tag' => 'sewing',
                'title' => 'sewing',
                'subtitle' => 'sewing',
                'meta_description' => 'sewing',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            102 => 
            array (
                'id' => 104,
                'tag' => 'textiles',
                'title' => 'textiles',
                'subtitle' => 'textiles',
                'meta_description' => 'textiles',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            103 => 
            array (
                'id' => 105,
                'tag' => 'sets',
                'title' => 'sets',
                'subtitle' => 'sets',
                'meta_description' => 'sets',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            104 => 
            array (
                'id' => 106,
                'tag' => 'cosplay',
                'title' => 'cosplay',
                'subtitle' => 'cosplay',
                'meta_description' => 'cosplay',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            105 => 
            array (
                'id' => 107,
                'tag' => 'shows',
                'title' => 'shows',
                'subtitle' => 'shows',
                'meta_description' => 'shows',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
            106 => 
            array (
                'id' => 108,
                'tag' => 'entertainment',
                'title' => 'entertainment',
                'subtitle' => 'entertainment',
                'meta_description' => 'entertainment',
                'layout' => 'canvas::frontend.blog.index',
                'reverse_direction' => 0,
                'created_at' => '2017-05-22 01:44:51',
                'updated_at' => '2017-05-22 01:44:51',
            ),
        ));
        
        
    }
}
